version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: commit_town_postgres
    environment:
      POSTGRES_DB: commit_town
      POSTGRES_USER: commit_town
      POSTGRES_PASSWORD: commit_town
    ports:
      - "5432:5432"
    volumes:
      - commit_town_data:/var/lib/postgresql/data

volumes:
  commit_town_data: